### ISSUE TITLE
Paths Design for Reservations

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [DevNetSandbox/sbx_api_issues#5]
The creation of a reservation should certainly be designed as:
POST /reservations

instead of POST /sandbox/reservations

**Comment by TomDaviesUK** [comment]
This is a good point. I feel this change might also make your points in #6 more viable, with the right naming.

Tagging @lookimapengu1 to investigate against and assess against the style guide, also.

**Comment by lookimapengu1** [comment]
Done, change is currently available in the dev environment for testing.
